[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Next.js App Router support
# Redirect API calls to Netlify functions
[[redirects]]
  from = "/api/ai/summarize"
  to = "/.netlify/functions/ai-summarize"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200