[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js App Router support
# The plugin handles API routes automatically
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200